
services:
  postgres:
    image: postgres:13
    container_name: olxdb_postgres
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
     - dbnet

  flyway:
      image: flyway/flyway:10-alpine
      depends_on:
        - postgres
      command: -url=jdbc:postgresql://postgres:5432/admin -user=admin -password=admin -schemas=public -baselineOnMigrate=true migrate
      volumes:
        - ./db/migration:/flyway/sql
      networks:
        - dbnet

networks:
  dbnet:

